apiVersion: v1
kind: Pod
metadata:
  name: busybox2-volumes
spec:
  volumes:
  - name: test
    emptyDir: {}
  containers:
  - name: busybox-1
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: test
      mountPath: /mount-1
  - name: busybox-2
    image: busybox
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: test
      mountPath: /mount-2
